-- Migration to expand clients table for comprehensive identity and tenancy details
ALTER TABLE clients 
ADD COLUMN IF NOT EXISTS company_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS trade_license VARCHAR(100),
ADD COLUMN IF NOT EXISTS tax_no VARCHAR(100),
ADD COLUMN IF NOT EXISTS industry VARCHAR(100),
ADD COLUMN IF NOT EXISTS logo VARCHAR(255),
ADD COLUMN IF NOT EXISTS tenancy_type VARCHAR(20) DEFAULT 'OWNED', -- OWNED, RENTED
ADD COLUMN IF NOT EXISTS landlord_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS contract_start_date DATE,
ADD COLUMN IF NOT EXISTS contract_end_date DATE,
ADD COLUMN IF NOT EXISTS registration_no VARCHAR(100), -- Ejari / Tawtheeq
ADD COLUMN IF NOT EXISTS ownership_doc_ref VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS area VARCHAR(255),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS po_box VARCHAR(50),
ADD COLUMN IF NOT EXISTS makani_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8),
ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8),
ADD COLUMN IF NOT EXISTS telephone VARCHAR(50),
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS website VARCHAR(255),
ADD COLUMN IF NOT EXISTS support_email VARCHAR(255);
