const db = require('./config/db');

async function migrate() {
    try {
        console.log('Starting migration to allow multiple sub-module configurations...');

        // 1. Drop the unique constraint/index
        // From our check, it might be named 'idx_company_module' or 'company_id' or 'module_id'
        // Based on SHOW INDEX FROM company_modules, Non_unique: 0 was found for 'idx_company_module' and 'company_id' (possibly generated by foreign keys or old schema)

        const indexesToDrop = ['idx_company_module', 'company_id'];

        for (const idx of indexesToDrop) {
            try {
                console.log(`Attempting to drop unique index: ${idx}`);
                await db.execute(`ALTER TABLE company_modules DROP INDEX ${idx}`);
                console.log(`Dropped index: ${idx}`);
            } catch (e) {
                console.log(`Could not drop index ${idx} (might not exist): ${e.message}`);
            }
        }

        // 2. Add non-unique index for performance
        console.log('Adding non-unique index for company_id + module_id...');
        await db.execute('ALTER TABLE company_modules ADD INDEX idx_company_module_search (company_id, module_id)');

        console.log('Migration completed successfully.');
        process.exit(0);
    } catch (error) {
        console.error('Migration failed:', error);
        process.exit(1);
    }
}

migrate();
