-- STEP 3: ADD CONSTRAINTS & INDEXES
CREATE UNIQUE INDEX "idx_assets_company_id" ON "assets" ("company_id", "asset_code");
CREATE INDEX "idx_assets_category_id" ON "assets" ("category_id");
CREATE INDEX "idx_assets_current_holder_id" ON "assets" ("current_holder_id");
CREATE INDEX "idx_assets_company_id_2" ON "assets" ("company_id");
CREATE INDEX "idx_asset_assignments_asset_id" ON "asset_assignments" ("asset_id");
CREATE INDEX "idx_asset_assignments_employee_id" ON "asset_assignments" ("employee_id");
CREATE INDEX "idx_asset_assignments_company_id" ON "asset_assignments" ("company_id");
CREATE INDEX "idx_asset_categories_company_id" ON "asset_categories" ("company_id");
CREATE INDEX "idx_asset_requests_employee_id" ON "asset_requests" ("employee_id");
CREATE INDEX "idx_asset_requests_company_id" ON "asset_requests" ("company_id");
CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("user_id");
CREATE INDEX "idx_audit_logs_company_id" ON "audit_logs" ("company_id");
CREATE UNIQUE INDEX "idx_companies_subdomain" ON "companies" ("subdomain");
CREATE INDEX "idx_company_modules_module_id" ON "company_modules" ("module_id");
CREATE INDEX "idx_company_modules_idx_country_id" ON "company_modules" ("country_id");
CREATE INDEX "idx_company_modules_idx_premises_type_id" ON "company_modules" ("premises_type_id");
CREATE INDEX "idx_company_modules_idx_area_id" ON "company_modules" ("area_id");
CREATE INDEX "idx_company_modules_idx_status_id" ON "company_modules" ("status_id");
CREATE INDEX "idx_company_modules_idx_company_module_search" ON "company_modules" ("company_id", "module_id");
CREATE INDEX "idx_company_modules_fk_cm_property_type" ON "company_modules" ("property_type_id");
CREATE INDEX "idx_company_module_field_selection_idx_cm" ON "company_module_field_selection" ("company_module_id");
CREATE INDEX "idx_company_module_field_selection_idx_field" ON "company_module_field_selection" ("field_id");
CREATE UNIQUE INDEX "idx_countries_uq_country_name" ON "countries" ("country_name");
CREATE INDEX "idx_departments_company_id" ON "departments" ("company_id");
CREATE INDEX "idx_employees_department_id" ON "employees" ("department_id");
CREATE INDEX "idx_employees_company_id" ON "employees" ("company_id");
CREATE INDEX "idx_maintenance_tickets_asset_id" ON "maintenance_tickets" ("asset_id");
CREATE INDEX "idx_maintenance_tickets_company_id" ON "maintenance_tickets" ("company_id");
CREATE UNIQUE INDEX "idx_modules_company_id_2" ON "modules" ("company_id", "module_key");
CREATE INDEX "idx_modules_company_id" ON "modules" ("company_id");
CREATE UNIQUE INDEX "idx_modules_master_module_key" ON "modules_master" ("module_key");
CREATE INDEX "idx_module_heads_template_id" ON "module_heads" ("template_id");
CREATE INDEX "idx_module_sections_company_id" ON "module_sections" ("company_id");
CREATE INDEX "idx_module_sections_module_id" ON "module_sections" ("module_id");
CREATE UNIQUE INDEX "idx_module_section_fields_unique_field_key" ON "module_section_fields" ("company_id", "section_id", "field_key");
CREATE INDEX "idx_module_section_fields_module_id" ON "module_section_fields" ("module_id");
CREATE INDEX "idx_module_section_fields_company_id" ON "module_section_fields" ("company_id");
CREATE INDEX "idx_module_section_fields_section_id" ON "module_section_fields" ("section_id");
CREATE INDEX "idx_module_section_field_options_field_id" ON "module_section_field_options" ("field_id");
CREATE INDEX "idx_module_subheads_head_id" ON "module_subheads" ("head_id");
CREATE INDEX "idx_module_subhead_options_subhead_id" ON "module_subhead_options" ("subhead_id");
CREATE INDEX "idx_module_templates_module_id" ON "module_templates" ("module_id");
CREATE INDEX "idx_module_templates_company_id" ON "module_templates" ("company_id");
CREATE INDEX "idx_office_premises_company_id" ON "office_premises" ("company_id");
CREATE INDEX "idx_office_premises_company_id_2" ON "office_premises" ("company_id", "premise_type");
CREATE INDEX "idx_office_premises_documents_company_id" ON "office_premises_documents" ("company_id");
CREATE INDEX "idx_office_premises_documents_company_id_2" ON "office_premises_documents" ("company_id", "premise_id");
CREATE INDEX "idx_office_premises_utilities_company_id" ON "office_premises_utilities" ("company_id");
CREATE INDEX "idx_office_premise_attachments_premise_id" ON "office_premise_attachments" ("premise_id");
CREATE INDEX "idx_office_premise_attachments_company_id" ON "office_premise_attachments" ("company_id");
CREATE INDEX "idx_premises_module_details_premise_id" ON "premises_module_details" ("premise_id");
CREATE INDEX "idx_premises_module_details_company_id" ON "premises_module_details" ("company_id");
CREATE UNIQUE INDEX "idx_property_types_name" ON "property_types" ("name");
CREATE UNIQUE INDEX "idx_users_company_id" ON "users" ("company_id", "email");
ALTER TABLE "assets" ADD CONSTRAINT "fk_assets_company_id_assets_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "assets" ADD CONSTRAINT "fk_assets_category_id_assets_ibfk_2" FOREIGN KEY ("category_id") REFERENCES "asset_categories" ("id") ON DELETE CASCADE;
ALTER TABLE "assets" ADD CONSTRAINT "fk_assets_current_holder_id_assets_ibfk_3" FOREIGN KEY ("current_holder_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "asset_assignments" ADD CONSTRAINT "fk_asset_assignments_company_id_asset_assignments_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "asset_assignments" ADD CONSTRAINT "fk_asset_assignments_asset_id_asset_assignments_ibfk_2" FOREIGN KEY ("asset_id") REFERENCES "assets" ("id") ON DELETE CASCADE;
ALTER TABLE "asset_assignments" ADD CONSTRAINT "fk_asset_assignments_employee_id_asset_assignments_ibfk_3" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "asset_categories" ADD CONSTRAINT "fk_asset_categories_company_id_asset_categories_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "asset_requests" ADD CONSTRAINT "fk_asset_requests_company_id_asset_requests_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "asset_requests" ADD CONSTRAINT "fk_asset_requests_employee_id_asset_requests_ibfk_2" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_company_id_audit_logs_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_user_id_audit_logs_ibfk_2" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "company_modules" ADD CONSTRAINT "fk_company_modules_company_id_company_modules_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "company_modules" ADD CONSTRAINT "fk_company_modules_module_id_company_modules_ibfk_2" FOREIGN KEY ("module_id") REFERENCES "modules_master" ("id") ON DELETE CASCADE;
ALTER TABLE "company_modules" ADD CONSTRAINT "fk_company_modules_property_type_id_fk_cm_property_type" FOREIGN KEY ("property_type_id") REFERENCES "property_types" ("id") ON DELETE CASCADE;
ALTER TABLE "company_module_field_selection" ADD CONSTRAINT "fk_company_module_field_selection_company_module_id_fk_cm_sel" FOREIGN KEY ("company_module_id") REFERENCES "company_modules" ("id") ON DELETE CASCADE;
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_company_id_departments_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_company_id_employees_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_department_id_employees_ibfk_2" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") ON DELETE CASCADE;
ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "fk_maintenance_tickets_company_id_maintenance_tickets_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "fk_maintenance_tickets_asset_id_maintenance_tickets_ibfk_2" FOREIGN KEY ("asset_id") REFERENCES "assets" ("id") ON DELETE CASCADE;
ALTER TABLE "modules" ADD CONSTRAINT "fk_modules_company_id_modules_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "module_heads" ADD CONSTRAINT "fk_module_heads_template_id_module_heads_ibfk_1" FOREIGN KEY ("template_id") REFERENCES "module_templates" ("id") ON DELETE CASCADE;
ALTER TABLE "module_sections" ADD CONSTRAINT "fk_module_sections_company_id_module_sections_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "module_sections" ADD CONSTRAINT "fk_module_sections_module_id_module_sections_ibfk_2" FOREIGN KEY ("module_id") REFERENCES "module_master" ("module_id") ON DELETE CASCADE;
ALTER TABLE "module_section_fields" ADD CONSTRAINT "fk_module_section_fields_company_id_module_section_fields_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "module_section_fields" ADD CONSTRAINT "fk_module_section_fields_module_id_module_section_fields_ibfk_2" FOREIGN KEY ("module_id") REFERENCES "module_master" ("module_id") ON DELETE CASCADE;
ALTER TABLE "module_section_fields" ADD CONSTRAINT "fk_module_section_fields_section_id_module_section_fields_ibfk_3" FOREIGN KEY ("section_id") REFERENCES "module_sections" ("id") ON DELETE CASCADE;
ALTER TABLE "module_section_field_options" ADD CONSTRAINT "fk_module_section_field_options_field_id_module_section_field_options_ibfk_1" FOREIGN KEY ("field_id") REFERENCES "module_section_fields" ("id") ON DELETE CASCADE;
ALTER TABLE "module_subheads" ADD CONSTRAINT "fk_module_subheads_head_id_module_subheads_ibfk_1" FOREIGN KEY ("head_id") REFERENCES "module_heads" ("id") ON DELETE CASCADE;
ALTER TABLE "module_subhead_options" ADD CONSTRAINT "fk_module_subhead_options_subhead_id_module_subhead_options_ibfk_1" FOREIGN KEY ("subhead_id") REFERENCES "module_subheads" ("id") ON DELETE CASCADE;
ALTER TABLE "module_templates" ADD CONSTRAINT "fk_module_templates_module_id_module_templates_ibfk_1" FOREIGN KEY ("module_id") REFERENCES "module_master" ("module_id") ON DELETE CASCADE;
ALTER TABLE "office_owned_details" ADD CONSTRAINT "fk_office_owned_details_premise_id_office_owned_details_ibfk_1" FOREIGN KEY ("premise_id") REFERENCES "office_premises" ("premise_id") ON DELETE CASCADE;
ALTER TABLE "office_premises" ADD CONSTRAINT "fk_office_premises_company_id_office_premises_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "office_premise_attachments" ADD CONSTRAINT "fk_office_premise_attachments_premise_id_office_premise_attachments_ibfk_1" FOREIGN KEY ("premise_id") REFERENCES "office_premises" ("premise_id") ON DELETE CASCADE;
ALTER TABLE "office_premise_attachments" ADD CONSTRAINT "fk_office_premise_attachments_company_id_office_premise_attachments_ibfk_2" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
ALTER TABLE "office_rental_details" ADD CONSTRAINT "fk_office_rental_details_premise_id_office_rental_details_ibfk_1" FOREIGN KEY ("premise_id") REFERENCES "office_premises" ("premise_id") ON DELETE CASCADE;
ALTER TABLE "users" ADD CONSTRAINT "fk_users_company_id_users_ibfk_1" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
